spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
api-key: 9c1e4b31a93d56f5e1aca1d21d9082b9
api-base-url: http://data.fixer.io/api
configuration:
  defaultSpread: 2.75
  baseCurrency: EUR
  spreads:
    JPY: 3.25
    HKD: 3.25
    KRW: 3.25
    MYR: 4.25
    INR: 4.25
    MXN: 4.25
    RUB: 6.0
    CNY: 6.0
    ZAR: 6.0